//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Choice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestOfTest
    {
        public int Id { get; set; }
        public int TestCode { get; set; }
        public int QuestionId { get; set; }
        public Nullable<System.DateTime> TimeStamps { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Test Test { get; set; }
    }
}
