//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Choice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Scores = new HashSet<Score>();
            this.StudentTestDetails = new HashSet<StudentTestDetail>();
        }
    
        public int StudentId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public int PermissionId { get; set; }
        public int ClassId { get; set; }
        public int SpecialityId { get; set; }
        public Nullable<int> IsTestting { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public string TimeRemaining { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastSeen { get; set; }
        public string LastSeenUrl { get; set; }
        public Nullable<System.DateTime> TimeStamps { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Permission Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        public virtual Speciality Speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTestDetail> StudentTestDetails { get; set; }
    }
}
