//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Choice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.QuestOfTests = new HashSet<QuestOfTest>();
            this.Scores = new HashSet<Score>();
        }
    
        public string TestName { get; set; }
        public int TestCode { get; set; }
        public string Password { get; set; }
        public int SubjectId { get; set; }
        public int QuestionsTotal { get; set; }
        public int TimeToDo { get; set; }
        public string Note { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> TimeStamps { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestOfTest> QuestOfTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        public virtual Status Status { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
